services:
  synapse:
    image: ghcr.io/element-hq/synapse:latest
    container_name: synapse
    hostname: synapse-server
    ports:
      - 8448:8448/tcp
      - ${SYNAPSE_HTTP_PORT}:${SYNAPSE_HTTP_PORT}
    stdin_open: true
    env_file:
      - .env
    tty: true
    volumes:
      - ./data:/data
      - ./data/logs:/data/logs
      - ./data/media_store:/data/media_store
      - ./data/ssl/:/data/ssl
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail --silent --show-error
          'http://${SYNAPSE_SERVER_NAME}:${SYNAPSE_HTTP_PORT}/_matrix/client/versions'
          || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      synapse-db:
        condition: service_healthy
    networks:
      - default

  synapse-db:
    container_name: synapse-db
    hostname: synapse-db-server
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - synapse-db:/data/postgres
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - default
  well-known:
    image: nginx:latest
    container_name: synapse-well-known
    hostname: synapse-wellknown-server
    env_file:
      - .env
    volumes:
      - ./data/well-known.conf:/etc/nginx/config/conf.d/default.conf
      - ./data/ssl:/etc/ssl
    ports:
      - ${WELL_KNOWN_HTTP_PORT}:443
    depends_on:
      synapse:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-k",
          "-f",
          "https://${SYNAPSE_SERVER_NAME}:${WELL_KNOWN_HTTP_PORT}/healthcheck",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default


  certbot:
    image: certbot/certbot:latest # Use the latest Certbot image
    profiles:
      - certbot
    container_name: certbot # Name the container 'certbot'
    hostname: certbot-server # Set the internal hostname of the container to 'certbot-server'
    volumes:
      - ./certs:/etc/letsencrypt # Mount the directory to store Let's Encrypt certificates
      - ./certs:/var/log/letsencrypt/ # Mount the directory to store Certbot logs
    command: certonly --standalone --force-renewal --email ${TTL_EMAIL} -d ${SYNAPSE_SERVER_NAME} --agree-tos
    networks:
      - default
    ports:
      - 80:80 # Expose port 80 externally to handle the HTTP challenge for certificate generation and renewal


volumes:
  synapse-db:
    name: synapse-db

networks:
  default:
    name: synapse-network
