services:
  certbot:
    image: certbot/certbot:latest # Use the latest Certbot image
    container_name: certbot # Name the container 'certbot'
    hostname: certbot-server # Set the internal hostname of the container to 'certbot-server'
    volumes:
      - ./certs:/etc/letsencrypt # Mount the directory to store Let's Encrypt certificates
      - ./logs:/var/log/letsencrypt # Separate directory for Certbot logs
    command:
      - certonly
      - --standalone
      - --force-renewal
      - --email
      - ${TTL_EMAIL}
      - -d
      - ${SYNAPSE_SERVER_NAME}
      - --agree-tos
    networks:
      - default
    ports:
      - 80:80 # Expose port 80 externally to handle the HTTP challenge for certificate generation and renewal
